print("I know how to use while loops")
print("I know how to use while loops")
print("I know how to use while loops")
print("I know how to use while loops")
print("I know how to use while loops")
print("I know how to use while loops")
print("I know how to use while loops")
print("I know how to use while loops")
print("I know how to use while loops")
print("I know how to use while loops")
print("I know how to use while loops")
print("I know how to use while loops")

